//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=SupermarketManagement;User ID=sa;Passwor" +
            "d=123;TrustServerCertificate=True")]
        public string SupermarketManagementConnectionString {
            get {
                return ((string)(this["SupermarketManagementConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supermarket Management")]
        public string StoreName {
            get {
                return ((string)(this["StoreName"]));
            }
            set {
                this["StoreName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Main Branch - Fresh & Quality Goods")]
        public string StoreBranch {
            get {
                return ((string)(this["StoreBranch"]));
            }
            set {
                this["StoreBranch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+855 12 345 678")]
        public string StorePhone {
            get {
                return ((string)(this["StorePhone"]));
            }
            set {
                this["StorePhone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("info@supermarket.com")]
        public string StoreEmail {
            get {
                return ((string)(this["StoreEmail"]));
            }
            set {
                this["StoreEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Phnom Penh, Cambodia")]
        public string StoreAddress {
            get {
                return ((string)(this["StoreAddress"]));
            }
            set {
                this["StoreAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.00")]
        public string TaxRate {
            get {
                return ((string)(this["TaxRate"]));
            }
            set {
                this["TaxRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$")]
        public string CurrencySymbol {
            get {
                return ((string)(this["CurrencySymbol"]));
            }
            set {
                this["CurrencySymbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4100")]
        public string ExchangeRate {
            get {
                return ((string)(this["ExchangeRate"]));
            }
            set {
                this["ExchangeRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thank you for shopping with us!")]
        public string ReceiptHeader {
            get {
                return ((string)(this["ReceiptHeader"]));
            }
            set {
                this["ReceiptHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Goods sold are not returnable. Please keep your receipt.")]
        public string ReceiptFooter {
            get {
                return ((string)(this["ReceiptFooter"]));
            }
            set {
                this["ReceiptFooter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LowStockThreshold {
            get {
                return ((int)(this["LowStockThreshold"]));
            }
            set {
                this["LowStockThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool AutoPrintReceipt {
            get {
                return ((bool)(this["AutoPrintReceipt"]));
            }
            set {
                this["AutoPrintReceipt"] = value;
            }
        }
    }
}
